### ISSUE TITLE
Secrets retrieved with `vault.generic.getSecret` are not treated as a Pulumi Secret

### ISSUE THREAD

**Issue by fernandocarletti** [pulumi/pulumi-vault#31] opened 2020-02-17 23:02 UTC
Take the following code as an example:

```typescript
import * as k8s from '@pulumi/kubernetes';
import * as vault from '@pulumi/vault';

const secrets = vault.generic.getSecret({
    path: `secret/pulumi-test`,
}).data;

const mySecret = secrets.mySecret;

const namespace =new k8s.core.v1.Namespace('test', {
    metadata: {
        labels: {
            foo: mySecret,
        }
    }
});
```

If you export the stack you can see that the `foo` label in the created namespace is not omitted.

Should we expect it to be encrypted in the state?

**Comment by lblackstone** [comment] 2020-02-25 19:35
It looks like the `data` property is not marked as a Pulumi secret in the SDK, which results in it being unencrypted in the state.

The namespace isn't directly relevant because the root cause is that the `mySecret` value isn't marked as secret.

You should be able to use the `additionalSecretOutputs` option to make this work. Can you try the following and see if that fixes it? (If not, that's a bug with the `get` method.)
```ts
const secrets = vault.generic.getSecret({
    path: `secret/pulumi-test`,
}, { 
    additionalSecretOutputs: ["data"]
}).data;
```

**Comment by lblackstone** [comment] 2020-02-25 20:17
https://github.com/pulumi/pulumi/issues/3976 may prevent this from working

**Comment by fernandocarletti** [comment] 2020-02-26 16:02
Hello @lblackstone. I actually tried that at first, but the `additionalSecretOutputs` property does not exists for it:
https://github.com/pulumi/pulumi-vault/blob/master/sdk/nodejs/generic/getSecret.ts#L10	
https://github.com/pulumi/pulumi/blob/master/sdk/nodejs/invoke.ts#L20

**Comment by lblackstone** [comment] 2020-02-26 16:13
@stack72 Any ideas?

**Comment by fernandocarletti** [comment] 2020-04-02 01:43
Hey guys. Any news here? :)

**Comment by lblackstone** [comment] 2020-04-06 21:19
@fernandocarletti Since the `additionalSecretOutputs` field doesn't exist for that method, you should be able to wrap the value with `pulumi.secret()` like this:

```ts
const secrets = pulumi.secret(vault.generic.getSecret({
    path: `secret/pulumi-test`,
}).data);
```

**Comment by lblackstone** [comment] 2020-04-06 21:35
I think manually wrapping the output with `pulumi.secret()` should solve the issue, so I'm closing this out for now. Feel free to reopen if that doesn't work for you.

**Closed by lblackstone** 2020-04-06 21:35 UTC

**Comment by lukehoban** [comment] 2020-04-06 21:41
Note that since `vault.generic.getSecret` returns prompt values, not `Outputs`, it actually currently *cannot* return secrets (since secretness is a bit on `Output`s).  So to "fix" this beyond the suggestion above, we would have to either change `getSecret` (and all data-source/function projections) to take and return `Outputs`, or offer an overload that did.

Note also that the call to `getSecret` is not stored in the checkpoint, so the typical need for `additionalSecretOutputs` instead of `pulumi.secret` - to prevent the outputs of the resource opertaion being written to the state file - doesn't apply.

So for now, wrapping with `pulumi.secret` is going to be the appropriate way to handle this.

**Comment by fernandocarletti** [comment] 2020-04-06 22:47
Thanks guys, I'll wrap the calls!
