### ISSUE TITLE
Support for bound_claims_type attribute in JWT backend role

### ISSUE THREAD

**Issue by bgagnon** [pulumi/pulumi-vault#84] opened 2020-10-27 17:50 UTC
Matching issue in the Terraform provider: terraform-providers/terraform-provider-vault#700.

**Comment by justinvp** [comment] 2020-10-27 17:58
Thanks for pointing this out and linking to the provider issue. We'll keep this open to track on our side.

**Comment by bgagnon** [comment] 2020-12-09 19:02
Just a heads up -- hashicorp/terraform-provider-vault#700 is fixed upstream.

**Comment by rajiteh** [comment] 2020-12-17 15:30
FYI the issue is fixed in the terraform provider [v2.17.0 ](https://github.com/hashicorp/terraform-provider-vault/releases/tag/v2.17.0)

**Comment by leezen** [comment] 2020-12-21 23:50
Fixed via https://github.com/pulumi/pulumi-vault/pull/91

**Closed by leezen** 2020-12-21 23:50 UTC
